[[Packmol]]
arch = "aarch64"
git-tree-sha1 = "fba7392c3a23330761de07c9032927613fde4cf8"
libgfortran_version = "5.0.0"
os = "macos"

    [[Packmol.download]]
    sha256 = "1b8f4fe752e960421e5939f7b5f7c563474cef28d6412fa810b0bcb1a8afff4e"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Packmol]]
arch = "aarch64"
git-tree-sha1 = "45546991c3e5cd790e5b8b64c14a84ce5904c305"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "c81ef3021391ccb3b27c78523e7892a6e915466af2b9299df4b68fbeea77f22d"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Packmol]]
arch = "aarch64"
git-tree-sha1 = "d138172aeae0a4473e481fd7a60a7f748ceb49b9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "a8686a9248286c8cb654dfcf3391bcf636f242c3fcecca5649755b93286b9083"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.aarch64-linux-musl-libgfortran5.tar.gz"
[[Packmol]]
arch = "aarch64"
git-tree-sha1 = "d8d0c04c6673c8cd76739d9971941fd01d0d7fbb"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Packmol.download]]
    sha256 = "0b8c580893bec2a8cbd41797fd6813990e1bf61b45ad24e68a116c480a2d8875"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[Packmol]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "94e87e850ca3038131a04b77ef0626fe49a65b55"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "93a0777d55d87e661c5262f7e004937d8682f6b0b6508f5fb39c262507a4c50a"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Packmol]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1567177e7999081406c284134945e6d3670d5272"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "380427d472d5b95a4281ee767eab4c4f11d96745d811eda4155bb8051e908d60"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Packmol]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "783b46e51a288033f8c39153bca8eaf078736885"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "591015458b18599ffd9e0278e3aaea2e9bbf0909309d2df1d4e137893418badd"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Packmol]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a45f387b3c03d83af9f180aa8e8f3d3a5c67ff0d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "21452973014b3a3c42c2b070f62b5c2728bf8f9e7dc48eb30a666447939b498e"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Packmol]]
arch = "i686"
git-tree-sha1 = "772bade4e39e81f2339367b083e3ea194d520819"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "0bd9990f4a0be96327ce3be5af9cbb27b10e849dc724ac1bdf359ae6940074e0"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.i686-linux-gnu-libgfortran5.tar.gz"
[[Packmol]]
arch = "i686"
git-tree-sha1 = "76ab53c3c94e69a9fb4b82ba6f478000493be5c3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "d4bfa16a30612c57c5a6a91cdb1ab7c20bc71ad5acde6430e6ca00eb59c89c2f"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.i686-linux-musl-libgfortran5.tar.gz"
[[Packmol]]
arch = "i686"
git-tree-sha1 = "5120759a16786e97a439016dd31f40eef952a551"
libgfortran_version = "5.0.0"
os = "windows"

    [[Packmol.download]]
    sha256 = "09613655f191afdaf429ebb1ddc3916c90a616b97c0a70502f97ab454bdf1f53"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[Packmol]]
arch = "powerpc64le"
git-tree-sha1 = "6b612e3aaffff32ed2b7cb92cf3f6a02ed2e7040"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "f653a3ed65040d604de7598d53e9bcf5bb0077b462a14e8a7e75953575e5f571"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Packmol]]
arch = "riscv64"
git-tree-sha1 = "d391c6d1514b408eefd83824e5ec705e345e0274"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "f2f65eb307510566abd7e8436b76b65e64e4a34ecbb6fdd3371dd87b847d7ad6"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.riscv64-linux-gnu-libgfortran5.tar.gz"
[[Packmol]]
arch = "x86_64"
git-tree-sha1 = "865ee94311633663fa403eaa8d19b25f5a9ea3de"
libgfortran_version = "5.0.0"
os = "macos"

    [[Packmol.download]]
    sha256 = "b2115c90c85c73c170de4860844eeb1905e8a5a298005974c12cc78d2acb55cd"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Packmol]]
arch = "x86_64"
git-tree-sha1 = "c25f61cf64a0c2124f0ce5acff703685a596bab6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "6603214a45878d645c8d92abb0ed1b4e7c429d8cde4c6f074f0472d5865b727c"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Packmol]]
arch = "x86_64"
git-tree-sha1 = "6cf9fa5d5138f19976c35afd3278701b7f529308"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Packmol.download]]
    sha256 = "8beb66232212a9839877ffc133e025445f83cc6f628358c26d73bee512cedd6b"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.x86_64-linux-musl-libgfortran5.tar.gz"
[[Packmol]]
arch = "x86_64"
git-tree-sha1 = "2767c627db663b30d5efa5998b431491575beadd"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Packmol.download]]
    sha256 = "b70436f697bc24dc5e507c24775f03e4d8c0ecd171c88ed3ae0e65376d45dbf2"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Packmol]]
arch = "x86_64"
git-tree-sha1 = "4fdaaabbb7b3bb6363fa6b9810da17508d1a670c"
libgfortran_version = "5.0.0"
os = "windows"

    [[Packmol.download]]
    sha256 = "525ae568e64134c85d14df94f5c2f7e8ec78db3f5832fb710147463f26eedc99"
    url = "https://github.com/JuliaBinaryWrappers/Packmol_jll.jl/releases/download/Packmol-v21.1.3+0/Packmol.v21.1.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
